---
# multi-cluster scylla-db
services:
  scylla-1:
    image: scylladb/scylla
    container_name: scylla-1
  scylla-2:
    image: scylladb/scylla
    container_name: scylla-2
    command: --seeds=some-scylla

  scylla-3:
    image: scylladb/scylla
    container_name: scylla-3
    command: --seeds=some-scylla

 